return {
	"chrisbra/csv.vim",
	{ "Shougo/denite.nvim", enable = false },
	"editorconfig/editorconfig-vim",
	"vito-c/jq.vim",
	"Shougo/neomru.vim",
	"scrooloose/nerdtree",
	"norcalli/nvim-colorizer.lua",
	{ "mfussenegger/nvim-dap", enable = false },
	"rcarriga/nvim-dap-ui",
	"nvim-tree/nvim-web-devicons",
	"puppetlabs/puppet-syntax-vim",
	"kkharji/sqlite.lua",
	"wellle/targets.vim",
	"tomtom/tcomment_vim",
	-- "SirVer/ultisnips",
	"ntpeters/vim-better-whitespace",
	"delphinus/vim-firestore",
	"tpope/vim-fugitive",
	"euclio/vim-markdown-composer",
	{ "patstockwell/vim-monokai-tasty", enable = false },
	"pantharshit00/vim-prisma",
	{ "JavierParra/vim-prosession",
		dependencies = "tpope/vim-obsession"
	},
	"tpope/vim-repeat",
	"sirosen/vim-rockstar",
	-- "tpope/vim-rsi",
	"tpope/vim-sleuth",
	"tpope/vim-surround",
	"dhruvasagar/vim-table-mode",
	"vimwiki/vimwiki",
	"nvim-lua/plenary.nvim",
}
